### ISSUE TITLE
Wifi not connecting

### ISSUE THREAD

**Issue by TerrifyingTaco** [xoration/ESPScale#4]
I'm not sure if I'm just doing something wrong or there's a bug in the code or something, but I was able to flash the firmware to the esp8266 just fine, but when I try to connect to it's wifi it gets stuck on "obtaining IP address"

**Comment by xoration** [comment]
Can you explain what you have done what you are trying to do, after you flashed the firmware.

**Comment by TerrifyingTaco** [comment]
I flashed the firmware through VScode/platformIO, and that worked fine with no errors, but I am unable to connect to the board with my phone. I've tried forcing my phone to use a static IP to get it to connect, but I still wasn't able to find the webpage through the mDNS name or the boards IP.

**Comment by xoration** [comment]
I mean can you connect to the wifi? It is still unclear to me what the problem is. What does the serial console say?

**Comment by xoration** [comment]
I guess the issue was resolved.
